### ISSUE TITLE
Constant-time entity creation

### ISSUE THREAD

**Issue by stasm** [piesku/goodluck#44]
Right now the `create` function has `O(n)` time complexity with `n` being the number of entities already existing in the world.

```ts
export function create(world: World, signature: number = 0) {
    for (let i = 0; i < MAX_ENTITIES; i++) {
        if (!world.Signature[i]) {
            world.Signature[i] = signature;
            return i;
        }
    }
    throw new Error("No more entities available.");
}
```

This might still be good enough for most use-cases we target, but I'd like to look into ways to optimize this. @ooflorent suggested an extra array storing the indices of destroyed entities. Let's call it `World.Graveyard`. When a new entity is requested, we first check the graveyard for an available index. If the graveyard is empty, we would use `World.Signature.length` as the next available index.

This is a fairly simple optimization in terms of complexity and codesize. The performance wins are well into one order of magnitude faster. However, I'm concerned about making entity creation dependent on the order of destroying entities. I think it might cause hard-to-debug bugs in `sys_transform` for example, which relies on the fact that parent entities are always updated before the children.

**Comment by ooflorent** [comment]
> I think it might cause hard-to-debug bugs in `sys_transform` for example, which relies on the fact that parent entities are always updated before the children.
This is already the case with the current implementation.

Consider the following scenario:

1. An entity is created `0`
2. Another entity is created alongside its children: `1` and `2`, `3`
3. `0` is destroyed
4. Another entity is created: it reuses `0`
5. `0` is added to `1` as a child

Here, `0` will be updated before its parent `1`.
