### ISSUE TITLE
Bootstrap Issues

### ISSUE THREAD

**Issue by bnicolucci** [piesku/goodluck#69]
When I use bootstrap to create a new project that is based off an example, I have a few problems. Many of the files it creates, loop.ts and entity.ts for example, are just links to files in the "core" folder, but during the bootstrap process, it deletes the "core" folder, so now the files no longer work.

Any idea why this is?

**Comment by stasm** [comment]
The idea behind symlinks is to make the maintenance of the template a bit easier for me. At the same time, I didn't want to bother the users of the projects generated from it with the added complexity; that's why `bootstrap.sh` removes the symlinks and replaces them with the files from `core`.

It sounds like the symlinks are only removed and not replaced for you? I just checked again, and the script works fine on my computer. Here's the output it produces:

```
$ ./bootstrap.sh FlyCamera/
Bootstrapping FlyCamera into src
  Removing other examples
    removing Animate/
    removing FlatShading/
    removing Instancing/
    removing Monkey/
    removing NewProject2D/
    removing NewProject3D/
    removing Particles/
    removing PathFinding/
    removing RenderTexture1/
    removing RenderTexture2/
    removing RigidBody/
    removing Shading/
    removing Texture/
    removing ThirdPerson/
    removing TodoApp/
    removing Trigger/
    removing WebXR/
  Replacing symlinks by the originals from core
    symlink found: FlyCamera/systems/sys_render1.ts
      replaced by: ../../core/systems/sys_render1.ts
    symlink found: FlyCamera/systems/sys_draw.ts
      replaced by: ../../core/systems/sys_draw.ts
    symlink found: FlyCamera/systems/sys_move.ts
      replaced by: ../../core/systems/sys_move.ts
    symlink found: FlyCamera/systems/sys_light.ts
      replaced by: ../../core/systems/sys_light.ts
    symlink found: FlyCamera/systems/sys_ui.ts
      replaced by: ../../core/systems/sys_ui.ts
    symlink found: FlyCamera/systems/sys_framerate.ts
      replaced by: ../../core/systems/sys_framerate.ts
    symlink found: FlyCamera/systems/sys_transform.ts
      replaced by: ../../core/systems/sys_transform.ts
    symlink found: FlyCamera/loop.ts
      replaced by: ../core/loop.ts
    symlink found: FlyCamera/entity.ts
      replaced by: ../core/entity.ts
    symlink found: FlyCamera/components/com_move.ts
      replaced by: ../../core/components/com_move.ts
    symlink found: FlyCamera/components/com_camera.ts
      replaced by: ../../core/components/com_camera.ts
    symlink found: FlyCamera/components/com_draw.ts
      replaced by: ../../core/components/com_draw.ts
    symlink found: FlyCamera/components/com_render1.ts
      replaced by: ../../core/components/com_render1.ts
    symlink found: FlyCamera/components/com_light.ts
      replaced by: ../../core/components/com_light.ts
    symlink found: FlyCamera/components/com_transform.ts
      replaced by: ../../core/components/com_transform.ts
  Removing core
  Renaming FlyCamera to src
  Updating README
  Removing other files
    removing CHANGELOG
    removing bootstrap.sh
  Committing to git
Done.
```

Do you see the same thing when you run `bootstrap.sh`? If not, can you paste your output please? Also, which OS are you on. I've tested the script on Windows using WSL, and on macOS.

**Comment by bnicolucci** [comment]
Ok, my output is definitely different and for some reason is not doing the Symlinks correctly. I'm on Windows 10. Looking in to why symlinks are failing on my side.
Here's my output:

$ ./bootstrap.sh NewProject3D
Bootstrapping NewProject3D into src
  Removing other examples
    removing Animate/
    removing FlatShading/
    removing FlyCamera/
    removing Instancing/
    removing Monkey/
    removing NewProject2D/
    removing Particles/
    removing PathFinding/
    removing RenderTexture1/
    removing RenderTexture2/
    removing RigidBody/
    removing Shading/
    removing Texture/
    removing ThirdPerson/
    removing TodoApp/
    removing Trigger/
    removing WebXR/
  Replacing symlinks by the originals from core
  Removing core
  Renaming NewProject3D to src
  Updating README
  Removing other files
    removing CHANGELOG
    removing bootstrap.sh
  Committing to git
Done.

**Comment by bnicolucci** [comment]
When I was cloning the repo, it was losing the symlinks, hence it failing. When I made my own symlinks as a test, it worked fine so using just a generic, git clone, it breaks the symlinks.
On Windows, it seems you need to do a:
git clone --config core.symlinks=true https://github.com/piesku/goodluck.git (or whatever the git repo is called)
for it to keep the symlinks.
Once I did that, bootstrap worked like a charm!
Hopefully that helps out anyone else with this issue because it was really making me pull my hair out, and I'm bald, lol.

**Comment by stasm** [comment]
Thanks for digging into this and finding the root cause. To clarify: it looks like you're using WSL to run `./bootstrap.sh`, but did you clone the repo from `cmd.exe` or Powershell?

**Comment by bnicolucci** [comment]
I was using Bash inside of VSCode. I tested again with cmd.exe and Powershell and both worked using the "--config core.symlinks=true" option. Symlinks came through properly

**Comment by stasm** [comment]
I updated the README in https://github.com/piesku/goodluck/commit/98a3deecc81119c5ab2251e029721da212870967 to mention the issue with symlinks on Windows. Even though I'm a Window user myself, I use WSL for Goodluck development and I wasn't aware of the problem. Thanks for reporting it!
